# Generated by Django 5.1.1 on 2024-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('address', models.SlugField(max_length=255, unique=True)),
                ('meta', models.TextField(max_length=400)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, upload_to='blog/thumbnails_%Y/')),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('T', 'Published'), ('F', 'Draft')], max_length=1)),
                ('read_time', models.SmallIntegerField()),
                ('created_at', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('open_conv', models.BooleanField(default=True, verbose_name='Open Converstaion')),
            ],
            options={
                'ordering': ('last_modified',),
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
