# Generated by Django 5.1.1 on 2024-09-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_status_comment_delete_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='show',
            new_name='status',
        ),
    ]
