# Generated by Django 5.1.1 on 2024-10-02 13:37

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_show_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_modified',
            field=django_jalali.db.models.jDateField(auto_now=True),
        ),
    ]
